- name: Update and upgrade apt packages
  hosts: all

  become: true

  tasks:
    - name: Update packages with apt
      apt:
        upgrade: yes
        update_cache: yes
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file
    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{ lookup('env', 'BOT_TOKEN') }}"
        api_args:
          chat_id: "{{ lookup('env', 'CHAT_ID') }}"
          parse_mode: "markdown"
          text: "Packages have been Updated, Reboot required"
          disable_web_page_preview: true
          disable_notification: true
      when: reboot_required_file.stat.exists == true
    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{ lookup('env', 'BOT_TOKEN') }}"
        api_args:
          chat_id: "{{ lookup('env', 'CHAT_ID') }}"
          parse_mode: "markdown"
          text: "Packages have been Updated, Reboot NOT required"
          disable_web_page_preview: true
          disable_notification: true
      when: reboot_required_file.stat.exists == false
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes