- name: Update and upgrade apt packages
  hosts: all

  become: true

  tasks:
    - name: Update packages with apt
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_update_result


    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Send update information to Telegram
      community.general.telegram:
        token: "{{ lookup('env', 'BOT_TOKEN') }}"
        api_args:
          chat_id: "{{ lookup('env', 'CHAT_ID') }}"
          parse_mode: "markdown"
          text: |
            "({{ ansible_hostname }} @ {{ ansible_host }}) Packages have been Updated, Reboot {{ 'required' if reboot_required_file.stat.exists else 'NOT required' }}.\n\n
            Number of updated packages: {{ apt_update_result | json_query('package_list | length') }}\n\n
            List of updated packages:\n
            {% for package in apt_update_result.package_list %}
              - {{ package.package }} ({{ package.current_version }} => {{ package.new_version }})
            {% endfor %}"


    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes